# Generated by Django 2.2.2 on 2019-07-11 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0002_auto_20190412_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={},
        ),
        migrations.AlterField(
            model_name='basket',
            name='add_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='время добавления'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Product', verbose_name='продукт'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='количество'),
        ),
    ]
