# Generated by Django 2.2.2 on 2019-07-02 15:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_auto_20190701_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 15, 36, 10, 135163, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
