# Generated by Django 2.2.2 on 2019-07-09 15:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0015_auto_20190702_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 11, 15, 58, 39, 678483, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
