# Generated by Django 2.2.2 on 2019-07-11 18:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0029_auto_20190711_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 13, 18, 4, 41, 812645, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
