# Generated by Django 2.2.2 on 2019-07-18 17:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0031_auto_20190712_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 20, 17, 31, 53, 734145, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
